"use client";

import React from "react";
import { usePapouDigitalContext } from "@/components/context/usePapouDigitalContext";

const PrivacyPolicyMain: React.FC = () => {
  const { locale } = usePapouDigitalContext();
  const isFr = locale === "fr";

  return (
    <section className="terms-page">
      <div className="container">
        <div className="terms-page__inner">
          <h1 className="terms-page__main-title">
            {isFr ? "PAPOUDIGITAL POLITIQUE DE CONFIDENTIALITÉ" : "PAPOUDIGITAL PRIVACY POLICY"}
          </h1>
          <p className="terms-page__meta">
            <strong>{isFr ? "Date d'effet :" : "Effective Date:"}</strong> February 2026
          </p>
          <p className="terms-page__meta">
            <strong>{isFr ? "Dernière mise à jour :" : "Last Updated:"}</strong> February 2026
          </p>

          {!isFr && (
            <>
              <div className="terms-page__section"><h2>1. INTRODUCTION</h2><p>PAPOUDIGITAL ("PAPOUDIGITAL", "Company", "we", "us", or "our") respects your privacy and is committed to protecting personal data in accordance with international data protection standards, including the General Data Protection Regulation (GDPR) and applicable African data protection laws.</p><p>This Privacy Policy explains how we collect, use, store, and protect personal information when you:</p><ul><li>Visit our website</li><li>Contact us</li><li>Use our services</li><li>Engage with our platforms</li><li>Apply to work with us</li><li>Interact with our digital solutions</li></ul><p>By using our services, you acknowledge this Privacy Policy.</p></div>
              <div className="terms-page__section"><h2>2. DATA CONTROLLER</h2><p>PAPOUDIGITAL acts as the Data Controller for personal data processed under this policy.</p><p><strong>Contact:</strong><br />Email: privacy@papoudigital.com<br />Website: www.papoudigital.com<br />Address: Rue Bassope, Be Kpota, Lome Togo</p></div>
              <div className="terms-page__section"><h2>3. INFORMATION WE COLLECT</h2><p><strong>3.1 Information You Provide</strong></p><p>We may collect:</p><ul><li>Full name</li><li>Company name</li><li>Email address</li><li>Phone or WhatsApp number</li><li>Billing information</li><li>Project details and communications</li><li>Account credentials (if applicable)</li></ul><p><strong>3.2 Automatically Collected Information</strong></p><p>When visiting our website:</p><ul><li>IP address</li><li>Device information</li><li>Browser type</li><li>Usage behavior</li><li>Pages visited</li><li>Cookies and analytics data</li></ul><p><strong>3.3 Information from Clients' Platforms</strong></p><p>When providing services, we may process data on behalf of clients as a Data Processor, including user or customer information necessary to deliver services.</p></div>
              <div className="terms-page__section"><h2>4. PURPOSE OF DATA PROCESSING</h2><p>We process personal data to:</p><ul><li>Provide and manage services</li><li>Communicate with clients and users</li><li>Deliver technical support</li><li>Improve website performance</li><li>Ensure platform security</li><li>Process payments and contracts</li><li>Recruit professionals</li><li>Comply with legal obligations</li></ul><p>We only collect data necessary for legitimate business purposes.</p></div>
              <div className="terms-page__section"><h2>5. LEGAL BASIS FOR PROCESSING (GDPR)</h2><p>Processing is based on:</p><ul><li>Contractual necessity</li><li>Legitimate business interests</li><li>Legal compliance obligations</li><li>User consent (where required)</li></ul></div>
              <div className="terms-page__section"><h2>6. DATA SHARING</h2><p>We do not sell personal data.</p><p>We may share data with trusted service providers including:</p><ul><li>Cloud hosting providers</li><li>Payment processors</li><li>Analytics services</li><li>Communication tools</li><li>Infrastructure partners</li></ul><p>All partners are required to maintain appropriate security standards.</p></div>
              <div className="terms-page__section"><h2>7. INTERNATIONAL DATA TRANSFERS</h2><p>Because PAPOUDIGITAL operates internationally, data may be transferred outside your country.</p><p>When transfers occur, we implement safeguards such as:</p><ul><li>Standard Contractual Clauses (SCCs)</li><li>Secure hosting environments</li><li>Encryption and access controls</li></ul></div>
              <div className="terms-page__section"><h2>8. DATA RETENTION</h2><p>We retain personal data only as long as necessary:</p><ul><li>Client data: duration of contract + legal retention period</li><li>Contact inquiries: up to 24 months</li><li>Recruitment data: up to 12 months unless consent is renewed</li><li>Analytics data: anonymized where possible</li></ul></div>
              <div className="terms-page__section"><h2>9. DATA SECURITY</h2><p>We implement enterprise-level safeguards including:</p><ul><li>Encryption in transit and at rest</li><li>Access control policies</li><li>Secure cloud infrastructure</li><li>Monitoring and incident prevention</li><li>Regular security updates</li></ul><p>However, no online system can guarantee absolute security.</p></div>
              <div className="terms-page__section"><h2>10. YOUR DATA RIGHTS</h2><p>Under GDPR and similar laws, you may:</p><ul><li>Request access to your data</li><li>Request correction</li><li>Request deletion ("Right to be forgotten")</li><li>Restrict processing</li><li>Object to processing</li><li>Request data portability</li><li>Withdraw consent at any time</li></ul><p>Requests may be sent to: privacy@papoudigital.com</p></div>
              <div className="terms-page__section"><h2>11. COOKIES AND TRACKING TECHNOLOGIES</h2><p>We use cookies to:</p><ul><li>Improve user experience</li><li>Analyze website performance</li><li>Maintain security</li><li>Remember preferences</li></ul><p>Users may control cookies through browser settings.</p><p>A cookie banner may be displayed where legally required.</p></div>
              <div className="terms-page__section"><h2>12. CHILDREN'S PRIVACY</h2><p>Our services are not directed toward individuals under 16 years old.</p><p>We do not knowingly collect personal data from minors.</p></div>
              <div className="terms-page__section"><h2>13. THIRD-PARTY LINKS</h2><p>Our website may contain links to third-party websites.</p><p>We are not responsible for their privacy practices.</p></div>
              <div className="terms-page__section"><h2>14. CLIENT DATA PROCESSING RESPONSIBILITIES</h2><p>When PAPOUDIGITAL processes data on behalf of clients:</p><ul><li>Clients remain Data Controllers.</li><li>PAPOUDIGITAL acts as Data Processor.</li><li>Processing occurs only under client instructions.</li></ul></div>
              <div className="terms-page__section"><h2>15. AI AND AUTOMATED PROCESSING</h2><p>Where AI technologies are used:</p><ul><li>AI outputs may involve automated processing.</li><li>No solely automated decisions producing legal effects are made without human oversight.</li><li>Clients remain responsible for validating AI-generated results.</li></ul></div>
              <div className="terms-page__section"><h2>16. DATA BREACH NOTIFICATION</h2><p>In the event of a data breach posing risk to individuals:</p><ul><li>We will investigate immediately.</li><li>Affected parties and authorities will be notified where required by law.</li></ul></div>
              <div className="terms-page__section"><h2>17. POLICY UPDATES</h2><p>We may update this Privacy Policy periodically.</p><p>Material changes will be communicated through our website.</p></div>
              <div className="terms-page__section"><h2>18. CONTACT</h2><p>For privacy-related questions or requests:</p><p><strong>PAPOUDIGITAL</strong><br />Email: privacy@papoudigital.com<br />Website: www.papoudigital.com<br />Address: Rue Bassope, Be Kpota, Lome Togo</p></div>
            </>
          )}

          {isFr && (
            <>
              <div className="terms-page__section"><h2>1. INTRODUCTION</h2><p>PAPOUDIGITAL ("PAPOUDIGITAL", "Société", "nous", "notre", "nos") respecte votre vie privée et s'engage à protéger les données personnelles conformément aux normes internationales de protection des données, y compris le Règlement Général sur la Protection des Données (RGPD) et les lois africaines applicables.</p><p>La présente Politique de Confidentialité explique comment nous collectons, utilisons, stockons et protégeons les informations personnelles lorsque vous :</p><ul><li>Visitez notre site web</li><li>Nous contactez</li><li>Utilisez nos services</li><li>Interagissez avec nos plateformes</li><li>Postulez pour collaborer avec nous</li><li>Interagissez avec nos solutions digitales</li></ul><p>En utilisant nos services, vous reconnaissez cette Politique de Confidentialité.</p></div>
              <div className="terms-page__section"><h2>2. RESPONSABLE DU TRAITEMENT</h2><p>PAPOUDIGITAL agit en tant que Responsable du traitement pour les données personnelles traitées dans le cadre de cette politique.</p><p><strong>Contact :</strong><br />Email : privacy@papoudigital.com<br />Site web : www.papoudigital.com<br />Adresse : Rue Bassope, Be Kpota, Lome Togo</p></div>
              <div className="terms-page__section"><h2>3. INFORMATIONS QUE NOUS COLLECTONS</h2><p><strong>3.1 Informations que vous fournissez</strong></p><p>Nous pouvons collecter :</p><ul><li>Nom complet</li><li>Nom de l'entreprise</li><li>Adresse e-mail</li><li>Numéro de téléphone ou WhatsApp</li><li>Informations de facturation</li><li>Détails du projet et communications</li><li>Identifiants de compte (le cas échéant)</li></ul><p><strong>3.2 Informations collectées automatiquement</strong></p><p>Lors de la visite de notre site web :</p><ul><li>Adresse IP</li><li>Informations sur l'appareil</li><li>Type de navigateur</li><li>Comportement d'utilisation</li><li>Pages visitées</li><li>Cookies et données analytiques</li></ul><p><strong>3.3 Informations provenant des plateformes des clients</strong></p><p>Lors de la fourniture de services, nous pouvons traiter des données pour le compte des clients en tant que Sous-traitant, y compris des informations utilisateurs ou clients nécessaires à la prestation des services.</p></div>
              <div className="terms-page__section"><h2>4. FINALITÉS DU TRAITEMENT</h2><p>Nous traitons les données personnelles afin de :</p><ul><li>Fournir et gérer les services</li><li>Communiquer avec les clients et utilisateurs</li><li>Assurer le support technique</li><li>Améliorer la performance du site</li><li>Assurer la sécurité des plateformes</li><li>Traiter les paiements et contrats</li><li>Recruter des professionnels</li><li>Respecter les obligations légales</li></ul><p>Nous collectons uniquement les données nécessaires à des finalités professionnelles légitimes.</p></div>
              <div className="terms-page__section"><h2>5. BASE LÉGALE DU TRAITEMENT (RGPD)</h2><p>Le traitement repose sur :</p><ul><li>La nécessité contractuelle</li><li>Les intérêts légitimes de l'entreprise</li><li>Les obligations légales</li><li>Le consentement de l'utilisateur (si requis)</li></ul></div>
              <div className="terms-page__section"><h2>6. PARTAGE DES DONNÉES</h2><p>Nous ne vendons pas les données personnelles.</p><p>Nous pouvons partager des données avec des prestataires de confiance, notamment :</p><ul><li>Fournisseurs d'hébergement cloud</li><li>Prestataires de paiement</li><li>Services analytiques</li><li>Outils de communication</li><li>Partenaires d'infrastructure</li></ul><p>Tous les partenaires sont tenus de maintenir des standards de sécurité appropriés.</p></div>
              <div className="terms-page__section"><h2>7. TRANSFERTS INTERNATIONAUX DE DONNÉES</h2><p>Puisque PAPOUDIGITAL opère à l'international, les données peuvent être transférées en dehors de votre pays.</p><p>Lorsque ces transferts ont lieu, nous mettons en place des garanties telles que :</p><ul><li>Clauses Contractuelles Types (SCC)</li><li>Environnements d'hébergement sécurisés</li><li>Chiffrement et contrôles d'accès</li></ul></div>
              <div className="terms-page__section"><h2>8. CONSERVATION DES DONNÉES</h2><p>Nous conservons les données personnelles uniquement pendant la durée nécessaire :</p><ul><li>Données client : durée du contrat + période légale de conservation</li><li>Demandes de contact : jusqu'à 24 mois</li><li>Données de recrutement : jusqu'à 12 mois sauf renouvellement du consentement</li><li>Données analytiques : anonymisées lorsque possible</li></ul></div>
              <div className="terms-page__section"><h2>9. SÉCURITÉ DES DONNÉES</h2><p>Nous mettons en œuvre des mesures de niveau entreprise, notamment :</p><ul><li>Chiffrement en transit et au repos</li><li>Politiques de contrôle d'accès</li><li>Infrastructure cloud sécurisée</li><li>Surveillance et prévention des incidents</li><li>Mises à jour de sécurité régulières</li></ul><p>Cependant, aucun système en ligne ne peut garantir une sécurité absolue.</p></div>
              <div className="terms-page__section"><h2>10. VOS DROITS</h2><p>Conformément au RGPD et aux lois similaires, vous pouvez :</p><ul><li>Demander l'accès à vos données</li><li>Demander la correction</li><li>Demander la suppression ("droit à l'oubli")</li><li>Limiter le traitement</li><li>Vous opposer au traitement</li><li>Demander la portabilité des données</li><li>Retirer votre consentement à tout moment</li></ul><p>Les demandes peuvent être envoyées à : privacy@papoudigital.com</p></div>
              <div className="terms-page__section"><h2>11. COOKIES ET TECHNOLOGIES DE SUIVI</h2><p>Nous utilisons des cookies pour :</p><ul><li>Améliorer l'expérience utilisateur</li><li>Analyser la performance du site</li><li>Maintenir la sécurité</li><li>Mémoriser les préférences</li></ul><p>Les utilisateurs peuvent gérer les cookies via les paramètres du navigateur.</p><p>Une bannière cookies peut être affichée lorsque la loi l'exige.</p></div>
              <div className="terms-page__section"><h2>12. CONFIDENTIALITÉ DES ENFANTS</h2><p>Nos services ne sont pas destinés aux personnes de moins de 16 ans.</p><p>Nous ne collectons pas sciemment de données personnelles de mineurs.</p></div>
              <div className="terms-page__section"><h2>13. LIENS TIERS</h2><p>Notre site web peut contenir des liens vers des sites tiers.</p><p>Nous ne sommes pas responsables de leurs pratiques de confidentialité.</p></div>
              <div className="terms-page__section"><h2>14. RESPONSABILITÉS DE TRAITEMENT DES DONNÉES CLIENT</h2><p>Lorsque PAPOUDIGITAL traite des données pour le compte des clients :</p><ul><li>Les clients restent Responsables du traitement.</li><li>PAPOUDIGITAL agit en tant que Sous-traitant.</li><li>Le traitement a lieu uniquement selon les instructions du client.</li></ul></div>
              <div className="terms-page__section"><h2>15. IA ET TRAITEMENT AUTOMATISÉ</h2><p>Lorsque des technologies d'IA sont utilisées :</p><ul><li>Les sorties IA peuvent impliquer un traitement automatisé.</li><li>Aucune décision exclusivement automatisée produisant des effets juridiques n'est prise sans supervision humaine.</li><li>Les clients restent responsables de la validation des résultats générés par l'IA.</li></ul></div>
              <div className="terms-page__section"><h2>16. NOTIFICATION DE VIOLATION DE DONNÉES</h2><p>En cas de violation de données présentant un risque pour les personnes :</p><ul><li>Nous enquêterons immédiatement.</li><li>Les parties concernées et autorités seront notifiées lorsque la loi l'exige.</li></ul></div>
              <div className="terms-page__section"><h2>17. MISES À JOUR DE LA POLITIQUE</h2><p>Nous pouvons mettre à jour cette Politique de Confidentialité périodiquement.</p><p>Les changements importants seront communiqués via notre site web.</p></div>
              <div className="terms-page__section"><h2>18. CONTACT</h2><p>Pour toute question ou demande liée à la confidentialité :</p><p><strong>PAPOUDIGITAL</strong><br />Email : privacy@papoudigital.com<br />Site web : www.papoudigital.com<br />Adresse : Rue Bassope, Be Kpota, Lome Togo</p></div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default PrivacyPolicyMain;
