"use client";

import React from "react";
import { usePapouDigitalContext } from "@/components/context/usePapouDigitalContext";

const TermsConditionsMain: React.FC = () => {
  const { locale } = usePapouDigitalContext();
  const isFr = locale === "fr";

  return (
    <section className="terms-page">
      <div className="container">
        <div className="terms-page__inner">
          <h1 className="terms-page__main-title">
            {isFr ? "PAPOUDIGITAL CONDITIONS GÉNÉRALES" : "PAPOUDIGITAL TERMS AND CONDITIONS"}
          </h1>
          <p className="terms-page__meta">
            <strong>{isFr ? "Date d'effet :" : "Effective Date:"}</strong> February 2026
          </p>
          <p className="terms-page__meta">
            <strong>{isFr ? "Dernière mise à jour :" : "Last Updated:"}</strong> February 2026
          </p>

          {!isFr && (
            <>
              <div className="terms-page__section"><h2>1. INTRODUCTION</h2><p>Welcome to PAPOUDIGITAL ("PAPOUDIGITAL", "Company", "we", "us", or "our").</p><p>These Terms and Conditions govern access to and use of our website, platforms, and all services provided by PAPOUDIGITAL, including digital development, consulting, cloud services, artificial intelligence solutions, ecommerce systems, payment integrations, automation, and related technology services.</p><p>By accessing our website or engaging our services, you agree to be bound by these Terms.</p></div>
              <div className="terms-page__section"><h2>2. DEFINITIONS</h2><ul><li><strong>User:</strong> Any individual accessing the website.</li><li><strong>Client:</strong> Any person or organization purchasing services.</li><li><strong>Developer/Contractor:</strong> Any professional collaborating with PAPOUDIGITAL.</li><li><strong>Services:</strong> All technological, consulting, and digital solutions offered.</li><li><strong>Deliverables:</strong> Software, designs, documentation, or systems produced.</li></ul></div>
              <div className="terms-page__section"><h2>3. SERVICES</h2><p>PAPOUDIGITAL provides professional technology services including:</p><ul><li>Web and mobile application development</li><li>Ecommerce and payment systems</li><li>Cloud infrastructure and migration</li><li>AI and automation solutions</li><li>Digital marketing and consulting</li><li>Maintenance and support services</li></ul><p>Each engagement may be governed by a proposal or Statement of Work (SOW).</p></div>
              <div className="terms-page__section"><h2>4. WEBSITE USE</h2><p>Users agree not to:</p><ul><li>Attempt unauthorized access</li><li>Distribute malicious software</li><li>Copy or reproduce content without permission</li><li>Use the website for unlawful activities</li></ul><p>We may suspend access for violations.</p></div>
              <div className="terms-page__section"><h2>5. CLIENT RESPONSIBILITIES</h2><p>Clients agree to:</p><ul><li>Provide accurate project information</li><li>Deliver required materials promptly</li><li>Review deliverables within reasonable timelines</li><li>Pay invoices according to agreed terms</li></ul><p>Project delays caused by missing client input may affect delivery schedules.</p></div>
              <div className="terms-page__section"><h2>6. PAYMENT TERMS</h2><ul><li>Payments follow agreed proposals or contracts.</li><li>Late payments may result in suspension of services.</li><li>Ownership transfer occurs only after full payment.</li><li>Fees are exclusive of taxes unless stated otherwise.</li></ul></div>
              <div className="terms-page__section"><h2>7. REFUND POLICY</h2><p>Unless explicitly stated in writing:</p><ul><li>Deposits and completed work are non-refundable.</li><li>Refunds are not provided for change of mind.</li><li>Partial refunds may be granted only if PAPOUDIGITAL fails to deliver agreed services.</li><li>Subscription services may be canceled at the next billing cycle.</li></ul></div>
              <div className="terms-page__section"><h2>8. INTELLECTUAL PROPERTY</h2><p>Upon full payment:</p><ul><li>Clients own final deliverables created specifically for them.</li><li>PAPOUDIGITAL retains ownership of internal frameworks, reusable components, and methodologies.</li><li>We reserve the right to showcase completed work in portfolios unless confidentiality is agreed.</li></ul></div>
              <div className="terms-page__section"><h2>9. CONFIDENTIALITY</h2><p>Both parties agree to protect confidential information and not disclose proprietary data without consent.</p><p>This obligation continues after termination.</p></div>
              <div className="terms-page__section"><h2>10. DATA PROTECTION</h2><p>We implement reasonable technical and organizational measures to protect data.</p><p>Clients remain responsible for compliance with laws governing data collected from their own users.</p></div>
              <div className="terms-page__section"><h2>11. SERVICE LEVEL AGREEMENT (SLA)</h2><p>Where support services are included:</p><p><strong>Availability</strong></p><p>Target service availability: 99% uptime monthly (excluding scheduled maintenance).</p><p><strong>Support Response Times</strong></p><ul><li>Critical issues: response within 4–8 business hours</li><li>Major issues: within 24 hours</li><li>Minor issues: within 48 hours</li></ul><p><strong>Maintenance Windows</strong></p><p>Scheduled maintenance may occur with prior notice.</p><p>SLA does not apply to failures caused by:</p><ul><li>Third-party providers</li><li>Client misuse</li><li>Internet outages beyond control</li></ul></div>
              <div className="terms-page__section"><h2>12. MAINTENANCE AGREEMENT</h2><p>Maintenance services may include:</p><ul><li>Security updates</li><li>Bug fixes</li><li>Performance monitoring</li><li>Minor improvements</li></ul><p>Maintenance does not include:</p><ul><li>Major redesigns</li><li>New feature development</li><li>Third-party licensing costs</li></ul><p>Maintenance plans renew automatically unless canceled.</p></div>
              <div className="terms-page__section"><h2>13. AI &amp; AUTOMATION SERVICES DISCLAIMER</h2><p>AI systems may generate probabilistic outputs.</p><p>PAPOUDIGITAL does not guarantee:</p><ul><li>Absolute accuracy</li><li>Legal or financial correctness of AI outputs</li></ul><p>Clients must review AI-generated results before operational use.</p></div>
              <div className="terms-page__section"><h2>14. OPEN-SOURCE USAGE POLICY</h2><p>Projects may include open-source software components.</p><p>Clients acknowledge that:</p><ul><li>Open-source licenses may apply.</li><li>Certain components remain publicly licensed.</li><li>PAPOUDIGITAL complies with applicable open-source licenses.</li></ul><p>We are not liable for external open-source project changes.</p></div>
              <div className="terms-page__section"><h2>15. THIRD-PARTY SERVICES</h2><p>We may integrate services such as hosting providers, payment gateways, APIs, and cloud infrastructure.</p><p>PAPOUDIGITAL is not responsible for outages or failures originating from third-party platforms.</p></div>
              <div className="terms-page__section"><h2>16. ACCEPTABLE USE POLICY</h2><p>Clients and Users must not use PAPOUDIGITAL services to:</p><ul><li>Conduct illegal activities</li><li>Distribute harmful or fraudulent content</li><li>Violate intellectual property rights</li><li>Send spam or malicious communications</li><li>Host abusive or discriminatory material</li></ul><p>Violation may result in immediate service suspension.</p></div>
              <div className="terms-page__section"><h2>17. DEVELOPER &amp; CONTRACTOR TERMS</h2><p>Developers and contractors agree to:</p><ul><li>Maintain confidentiality</li><li>Deliver professional work standards</li><li>Transfer intellectual property rights to PAPOUDIGITAL</li><li>Avoid direct solicitation of clients</li></ul><p>All work created within engagements belongs to PAPOUDIGITAL unless agreed otherwise.</p></div>
              <div className="terms-page__section"><h2>18. NON-SOLICITATION</h2><p>Clients agree not to directly hire PAPOUDIGITAL contractors during engagement and for 12 months after completion without written approval.</p></div>
              <div className="terms-page__section"><h2>19. LIMITATION OF LIABILITY</h2><p>To the maximum extent permitted by law, PAPOUDIGITAL shall not be liable for:</p><ul><li>Indirect or consequential damages</li><li>Loss of profits or business interruption</li><li>Data loss beyond reasonable control</li></ul><p>Total liability shall not exceed the amount paid for the specific service.</p></div>
              <div className="terms-page__section"><h2>20. FORCE MAJEURE</h2><p>We are not responsible for delays caused by events beyond reasonable control, including natural disasters, infrastructure failures, or governmental actions.</p></div>
              <div className="terms-page__section"><h2>21. COOKIE POLICY</h2><p>Our website uses cookies to:</p><ul><li>Improve performance</li><li>Analyze usage</li><li>Enhance user experience</li></ul><p>Users may disable cookies via browser settings; some features may be affected.</p></div>
              <div className="terms-page__section"><h2>22. MODIFICATIONS</h2><p>We may update these Terms at any time. Continued use of services constitutes acceptance of updates.</p></div>
              <div className="terms-page__section"><h2>23. GOVERNING LAW</h2><p>These Terms shall be governed by the laws of:</p><p>[Insert Jurisdiction — e.g., Republic of Togo / France / United States]</p><p>Disputes shall first attempt amicable resolution before legal proceedings.</p></div>
              <div className="terms-page__section"><h2>24. CONTACT</h2><p><strong>PAPOUDIGITAL</strong></p><p>Email: info@papoudigital.com</p><p>Website: www.papoudigital.com</p><p>Address: Rue Bassope, Be Kpota, Lome Togo</p></div>
            </>
          )}

          {isFr && (
            <>
              <div className="terms-page__section"><h2>1. INTRODUCTION</h2><p>Bienvenue chez PAPOUDIGITAL ("PAPOUDIGITAL", "Société", "nous", "notre", "nos").</p><p>Les présentes Conditions Générales régissent l'accès et l'utilisation de notre site web, de nos plateformes et de l'ensemble des services fournis par PAPOUDIGITAL, y compris le développement digital, le conseil, les services cloud, les solutions d'intelligence artificielle, les systèmes e-commerce, les intégrations de paiement, l'automatisation et les services technologiques associés.</p><p>En accédant à notre site web ou en utilisant nos services, vous acceptez d'être lié par les présentes Conditions.</p></div>
              <div className="terms-page__section"><h2>2. DÉFINITIONS</h2><ul><li><strong>Utilisateur :</strong> Toute personne accédant au site web.</li><li><strong>Client :</strong> Toute personne ou organisation achetant des services.</li><li><strong>Développeur/Prestataire :</strong> Tout professionnel collaborant avec PAPOUDIGITAL.</li><li><strong>Services :</strong> Toutes les solutions technologiques, de conseil et digitales proposées.</li><li><strong>Livrables :</strong> Logiciels, designs, documentation ou systèmes produits.</li></ul></div>
              <div className="terms-page__section"><h2>3. SERVICES</h2><p>PAPOUDIGITAL fournit des services technologiques professionnels, notamment :</p><ul><li>Développement d'applications web et mobiles</li><li>Systèmes e-commerce et de paiement</li><li>Infrastructure cloud et migration</li><li>Solutions IA et automatisation</li><li>Marketing digital et conseil</li><li>Services de maintenance et de support</li></ul><p>Chaque engagement peut être régi par une proposition ou un cahier des charges (SOW).</p></div>
              <div className="terms-page__section"><h2>4. UTILISATION DU SITE WEB</h2><p>Les utilisateurs s'engagent à ne pas :</p><ul><li>Tenter d'obtenir un accès non autorisé</li><li>Distribuer des logiciels malveillants</li><li>Copier ou reproduire du contenu sans autorisation</li><li>Utiliser le site web à des fins illégales</li></ul><p>Nous pouvons suspendre l'accès en cas de violation.</p></div>
              <div className="terms-page__section"><h2>5. RESPONSABILITÉS DU CLIENT</h2><p>Les clients s'engagent à :</p><ul><li>Fournir des informations de projet exactes</li><li>Fournir les éléments requis dans les délais</li><li>Examiner les livrables dans des délais raisonnables</li><li>Payer les factures selon les conditions convenues</li></ul><p>Les retards de projet causés par l'absence d'éléments du client peuvent affecter les délais de livraison.</p></div>
              <div className="terms-page__section"><h2>6. CONDITIONS DE PAIEMENT</h2><ul><li>Les paiements suivent les propositions ou contrats convenus.</li><li>Les retards de paiement peuvent entraîner la suspension des services.</li><li>Le transfert de propriété intervient uniquement après paiement intégral.</li><li>Les frais sont hors taxes, sauf mention contraire.</li></ul></div>
              <div className="terms-page__section"><h2>7. POLITIQUE DE REMBOURSEMENT</h2><p>Sauf mention expresse écrite :</p><ul><li>Les acomptes et travaux terminés ne sont pas remboursables.</li><li>Aucun remboursement n'est accordé pour changement d'avis.</li><li>Un remboursement partiel peut être accordé uniquement si PAPOUDIGITAL ne livre pas les services convenus.</li><li>Les services par abonnement peuvent être résiliés au prochain cycle de facturation.</li></ul></div>
              <div className="terms-page__section"><h2>8. PROPRIÉTÉ INTELLECTUELLE</h2><p>Après paiement intégral :</p><ul><li>Le client est propriétaire des livrables finaux créés spécifiquement pour lui.</li><li>PAPOUDIGITAL conserve la propriété de ses frameworks internes, composants réutilisables et méthodologies.</li><li>Nous nous réservons le droit de présenter les travaux finalisés dans nos portfolios, sauf accord de confidentialité.</li></ul></div>
              <div className="terms-page__section"><h2>9. CONFIDENTIALITÉ</h2><p>Les deux parties s'engagent à protéger les informations confidentielles et à ne pas divulguer de données propriétaires sans consentement.</p><p>Cette obligation se poursuit après la fin du contrat.</p></div>
              <div className="terms-page__section"><h2>10. PROTECTION DES DONNÉES</h2><p>Nous mettons en place des mesures techniques et organisationnelles raisonnables pour protéger les données.</p><p>Les clients restent responsables du respect des lois applicables aux données collectées auprès de leurs propres utilisateurs.</p></div>
              <div className="terms-page__section"><h2>11. ACCORD DE NIVEAU DE SERVICE (SLA)</h2><p>Lorsque des services de support sont inclus :</p><p><strong>Disponibilité</strong></p><p>Disponibilité cible : 99 % de disponibilité mensuelle (hors maintenance planifiée).</p><p><strong>Délais de réponse du support</strong></p><ul><li>Incidents critiques : réponse sous 4 à 8 heures ouvrées</li><li>Incidents majeurs : sous 24 heures</li><li>Incidents mineurs : sous 48 heures</li></ul><p><strong>Fenêtres de maintenance</strong></p><p>La maintenance planifiée peut avoir lieu avec préavis.</p><p>Le SLA ne s'applique pas aux défaillances causées par :</p><ul><li>Des fournisseurs tiers</li><li>Une mauvaise utilisation du client</li><li>Des coupures Internet hors de notre contrôle</li></ul></div>
              <div className="terms-page__section"><h2>12. CONTRAT DE MAINTENANCE</h2><p>Les services de maintenance peuvent inclure :</p><ul><li>Mises à jour de sécurité</li><li>Corrections de bugs</li><li>Surveillance des performances</li><li>Améliorations mineures</li></ul><p>La maintenance n'inclut pas :</p><ul><li>Refontes majeures</li><li>Développement de nouvelles fonctionnalités</li><li>Coûts de licences tierces</li></ul><p>Les plans de maintenance se renouvellent automatiquement sauf résiliation.</p></div>
              <div className="terms-page__section"><h2>13. CLAUSE DE NON-RESPONSABILITÉ IA &amp; AUTOMATISATION</h2><p>Les systèmes d'IA peuvent générer des résultats probabilistes.</p><p>PAPOUDIGITAL ne garantit pas :</p><ul><li>Une exactitude absolue</li><li>La validité juridique ou financière des résultats de l'IA</li></ul><p>Les clients doivent vérifier les résultats générés par l'IA avant toute utilisation opérationnelle.</p></div>
              <div className="terms-page__section"><h2>14. POLITIQUE D'UTILISATION OPEN SOURCE</h2><p>Les projets peuvent inclure des composants logiciels open source.</p><p>Les clients reconnaissent que :</p><ul><li>Des licences open source peuvent s'appliquer.</li><li>Certains composants restent sous licence publique.</li><li>PAPOUDIGITAL respecte les licences open source applicables.</li></ul><p>Nous ne sommes pas responsables des changements externes des projets open source.</p></div>
              <div className="terms-page__section"><h2>15. SERVICES TIERS</h2><p>Nous pouvons intégrer des services tels que des hébergeurs, passerelles de paiement, API et infrastructures cloud.</p><p>PAPOUDIGITAL n'est pas responsable des pannes ou défaillances provenant de plateformes tierces.</p></div>
              <div className="terms-page__section"><h2>16. POLITIQUE D'UTILISATION ACCEPTABLE</h2><p>Les clients et utilisateurs ne doivent pas utiliser les services de PAPOUDIGITAL pour :</p><ul><li>Mener des activités illégales</li><li>Diffuser du contenu nuisible ou frauduleux</li><li>Violer des droits de propriété intellectuelle</li><li>Envoyer du spam ou des communications malveillantes</li><li>Héberger du contenu abusif ou discriminatoire</li></ul><p>Toute violation peut entraîner une suspension immédiate du service.</p></div>
              <div className="terms-page__section"><h2>17. CONDITIONS POUR DÉVELOPPEURS &amp; PRESTATAIRES</h2><p>Les développeurs et prestataires s'engagent à :</p><ul><li>Maintenir la confidentialité</li><li>Fournir un travail professionnel</li><li>Transférer les droits de propriété intellectuelle à PAPOUDIGITAL</li><li>Éviter toute sollicitation directe des clients</li></ul><p>Tout travail créé dans le cadre des engagements appartient à PAPOUDIGITAL sauf accord contraire.</p></div>
              <div className="terms-page__section"><h2>18. NON-SOLLICITATION</h2><p>Les clients s'engagent à ne pas recruter directement les prestataires de PAPOUDIGITAL pendant l'engagement et pendant 12 mois après sa fin sans autorisation écrite.</p></div>
              <div className="terms-page__section"><h2>19. LIMITATION DE RESPONSABILITÉ</h2><p>Dans la limite maximale autorisée par la loi, PAPOUDIGITAL ne pourra être tenu responsable de :</p><ul><li>Dommages indirects ou consécutifs</li><li>Perte de profits ou interruption d'activité</li><li>Perte de données hors de notre contrôle raisonnable</li></ul><p>La responsabilité totale ne peut excéder le montant payé pour le service concerné.</p></div>
              <div className="terms-page__section"><h2>20. FORCE MAJEURE</h2><p>Nous ne sommes pas responsables des retards causés par des événements hors de notre contrôle raisonnable, y compris les catastrophes naturelles, défaillances d'infrastructure ou actions gouvernementales.</p></div>
              <div className="terms-page__section"><h2>21. POLITIQUE DE COOKIES</h2><p>Notre site web utilise des cookies pour :</p><ul><li>Améliorer les performances</li><li>Analyser l'utilisation</li><li>Améliorer l'expérience utilisateur</li></ul><p>Les utilisateurs peuvent désactiver les cookies via les paramètres du navigateur ; certaines fonctionnalités peuvent être affectées.</p></div>
              <div className="terms-page__section"><h2>22. MODIFICATIONS</h2><p>Nous pouvons mettre à jour les présentes Conditions à tout moment. La poursuite de l'utilisation des services vaut acceptation des mises à jour.</p></div>
              <div className="terms-page__section"><h2>23. DROIT APPLICABLE</h2><p>Les présentes Conditions sont régies par les lois de :</p><p>[Insert Jurisdiction — e.g., Republic of Togo / France / United States]</p><p>Les litiges feront d'abord l'objet d'une tentative de résolution amiable avant toute procédure judiciaire.</p></div>
              <div className="terms-page__section"><h2>24. CONTACT</h2><p><strong>PAPOUDIGITAL</strong></p><p>Email : info@papoudigital.com</p><p>Site web : www.papoudigital.com</p><p>Adresse : Rue Bassope, Be Kpota, Lome Togo</p></div>
            </>
          )}
        </div>
      </div>
    </section>
  );
};

export default TermsConditionsMain;
